// Code generated by sumeru-import-gen; DO NOT EDIT.

package ormmodels

import (
	"sumeru/core/modelreg"
	"sumeru/core/orm"
)

func init() {
	modelreg.MustRegister("base",
		&orm.AppLog{},
		&orm.SysAccess{},
		&orm.SysActionWindow{},
		&orm.SysApprovalRule{},
		&orm.SysField{},
		&orm.SysMenu{},
		&orm.SysModel{},
		&orm.SysModelData{},
		&orm.SysModule{},
		&orm.SysModuleCategory{},
		&orm.SysOutboxEvent{},
		&orm.SysRule{},
		&orm.SysSavedSearch{},
		&orm.SysSession{},
		&orm.SysView{},
	)
}
