// Code generated by sumeru-import-gen; DO NOT EDIT.

package main

import (
	_ "sumeru/addons/base"
	_ "sumeru/addons/contacts"
	_ "sumeru/addons/currency"
	_ "sumeru/addons/geo"
	_ "sumeru/addons/i18n"
	_ "sumeru/addons/im"
	_ "sumeru/addons/calendar"
	_ "sumeru/addons/digest"
	_ "sumeru/addons/platform"
	_ "sumeru/addons/audit"
	_ "sumeru/addons/automation"
	_ "sumeru/addons/uom"
)
