// Code generated by sumeru-import-gen; DO NOT EDIT.

package main

import (
	_ "sumeru/addons/base"
	_ "sumeru/addons/contacts"
	_ "sumeru/addons/mail"
	_ "sumeru/addons/automation"
	_ "sumeru/addons/calendar"
	_ "sumeru/addons/digest"
)
