// Code generated by sumeru-import-gen; DO NOT EDIT.

package orm

import "sumeru/core/modelmeta"

// CoreGroup → core.group
type CoreGroup struct {
	modelmeta.ModelMeta `sumeru:"model=core.group"`
}

// CoreUser → core.user
type CoreUser struct {
	modelmeta.ModelMeta `sumeru:"model=core.user"`
}

