package importgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"sumeru/core/module"
)

var initSubpackages = []string{"models", "services", "wizard", "controllers"}

func writeAddonInit(discovered map[string]*module.Addon, addon *module.Addon) error {
	if isBuiltinAddonPath(addon.Path) {
		return nil
	}
	imports, err := collectInitImports(discovered, addon)
	if err != nil {
		return err
	}
	body := renderAddonInit(addon.Manifest.Name, imports)
	dest := filepath.Join(addon.Path, "init.go")
	return os.WriteFile(dest, []byte(body), 0o644)
}

func collectInitImports(discovered map[string]*module.Addon, addon *module.Addon) ([]string, error) {
	seen := map[string]struct{}{}
	var imports []string

	addImport := func(importPath string) {
		importPath = strings.TrimSpace(importPath)
		if importPath == "" {
			return
		}
		if _, ok := seen[importPath]; ok {
			return
		}
		seen[importPath] = struct{}{}
		imports = append(imports, importPath)
	}

	for _, depName := range module.OrderedManifestDepends(discovered, addon.Manifest.Name) {
		dep, ok := discovered[depName]
		if !ok {
			continue
		}
		importPath, err := module.PackageImportPath(dep.Path)
		if err != nil {
			return nil, fmt.Errorf("depends %q: %w", depName, err)
		}
		addImport(importPath)
	}

	for _, sub := range initSubpackages {
		dir := filepath.Join(addon.Path, sub)
		hasGo, err := dirHasGoSource(dir)
		if err != nil {
			return nil, err
		}
		if !hasGo {
			continue
		}
		importPath, err := module.PackageImportPath(dir)
		if err != nil {
			return nil, fmt.Errorf("subpackage %q: %w", sub, err)
		}
		addImport(importPath)
	}

	return imports, nil
}

func dirHasGoSource(dir string) (bool, error) {
	st, err := os.Stat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	if !st.IsDir() {
		return false, nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") &&
			name != "zmodels.go" && name != "zrefs.go" {
			return true, nil
		}
	}
	return false, nil
}

func renderAddonInit(packageName string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(packageName)
	b.WriteString("\n\nimport (\n")
	for _, p := range imports {
		b.WriteString("\t_ \"")
		b.WriteString(p)
		b.WriteString("\"\n")
	}
	b.WriteString(")\n")
	return b.String()
}

// CollectInitImportsForTest exposes collectInitImports for tests.
func CollectInitImportsForTest(discovered map[string]*module.Addon, addon *module.Addon) ([]string, error) {
	return collectInitImports(discovered, addon)
}

// RenderAddonInitForTest exposes renderAddonInit for tests.
func RenderAddonInitForTest(packageName string, imports []string) string {
	return renderAddonInit(packageName, imports)
}
