package importgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sumeru/core/modelmeta"
)

func buildORMModelsGo(module string, types []string) string {
	if len(types) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\npackage ormmodels\n\nimport (\n\t\"sumeru/core/modelreg\"\n\t\"sumeru/core/orm\"\n)\n\nfunc init() {\n\tmodelreg.MustRegister(\"")
	b.WriteString(module)
	b.WriteString("\",\n")
	for _, t := range types {
		b.WriteString("\t\t&orm.")
		b.WriteString(t)
		b.WriteString("{},\n")
	}
	b.WriteString("\t)\n}\n")
	return b.String()
}

func buildPackageModelsGo(module string, types []string, packageName string) string {
	if len(types) == 0 {
		return ""
	}
	if packageName == "" {
		packageName = "models"
	}
	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\npackage ")
	b.WriteString(packageName)
	b.WriteString("\n\nimport \"sumeru/core/sdk\"\n\nfunc init() {\n")
	b.WriteString("\tsdk.MustRegister(\"")
	b.WriteString(module)
	b.WriteString("\",\n")
	for _, t := range types {
		b.WriteString("\t\t&")
		b.WriteString(t)
		b.WriteString("{},\n")
	}
	b.WriteString("\t)\n}\n")
	return b.String()
}

func writeAddonModelFiles(addonRoot, module string) error {
	pkgName := filepath.Base(addonRoot)
	if types, err := scanPackageForModels(addonRoot); err == nil && len(types) > 0 {
		body := buildPackageModelsGo(module, types, pkgName)
		dest := filepath.Join(addonRoot, "zmodels.go")
		if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", dest, err)
		}
	}
	for _, sub := range []string{"models", "wizard"} {
		dir := filepath.Join(addonRoot, sub)
		types, err := scanPackageForModels(dir)
		if err != nil || len(types) == 0 {
			continue
		}
		body := buildPackageModelsGo(module, types, packageNameForDir(dir))
		dest := filepath.Join(dir, "zmodels.go")
		if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", dest, err)
		}
	}
	return nil
}

func writeORMModelsRegistration(ormDir, ormmodelsDir, module string) error {
	types, err := scanPackageForModels(ormDir)
	if err != nil || len(types) == 0 {
		return nil
	}
	body := buildORMModelsGo(module, types)
	if err := os.MkdirAll(ormmodelsDir, 0o755); err != nil {
		return err
	}
	dest := filepath.Join(ormmodelsDir, "zmodels.go")
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", dest, err)
	}
	return nil
}

func writeORMZRefs(ormDir string) error {
	used, err := scanUsedRelationTypes(ormDir)
	if err != nil {
		return err
	}
	local, err := scanPackageForModels(ormDir)
	if err != nil {
		return err
	}
	localSet := map[string]struct{}{}
	for _, name := range local {
		localSet[name] = struct{}{}
	}

	var names []string
	for name := range used {
		if _, ok := localSet[name]; ok {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	zrefsPath := filepath.Join(ormDir, "zrefs.go")
	if len(names) == 0 {
		_ = os.Remove(zrefsPath)
		return nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\npackage orm\n\nimport \"sumeru/core/modelmeta\"\n\n")
	for _, name := range names {
		technical := modelmeta.ModelNameFromGo(name)
		fmt.Fprintf(&b, "// %s → %s\n", name, technical)
		fmt.Fprintf(&b, "type %s struct {\n\tmodelmeta.ModelMeta `sumeru:\"model=%s\"`\n}\n\n", name, technical)
	}
	return os.WriteFile(zrefsPath, []byte(b.String()), 0o644)
}
