package importgen

import (
	"fmt"
	"sort"
	"strings"
)

func importAliasForPath(importPath string) string {
	parts := strings.Split(importPath, "/")
	last := parts[len(parts)-1]
	if last == "models" || last == "orm" || last == "wizard" {
		if len(parts) >= 2 {
			last = parts[len(parts)-2] + last
		}
	}
	last = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, last)
	if last == "" {
		return "refpkg"
	}
	if last[0] >= '0' && last[0] <= '9' {
		last = "ref" + last
	}
	return strings.ToLower(last[:1]) + last[1:]
}

func renderZRefs(refs []exportedRef) string {
	if len(refs) == 0 {
		return ""
	}

	imports := map[string]string{}
	for _, ref := range refs {
		if ref.Kind == "alias" {
			imports[ref.ImportPath] = ref.ImportAlias
		}
	}
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\n")
	b.WriteString("package models\n\n")
	b.WriteString("import (\n")
	needsSDK := false
	for _, ref := range refs {
		if ref.Kind == "phantom" {
			needsSDK = true
			break
		}
	}
	if needsSDK {
		b.WriteString("\t\"sumeru/core/sdk\"\n")
	}
	for _, p := range paths {
		b.WriteString(fmt.Sprintf("\t%s %q\n", imports[p], p))
	}
	b.WriteString(")\n\n")

	sort.Slice(refs, func(i, j int) bool { return refs[i].Name < refs[j].Name })
	for _, ref := range refs {
		switch ref.Kind {
		case "alias":
			b.WriteString(fmt.Sprintf("// %s → %s\n", ref.Name, ref.TechnicalModel))
			b.WriteString(fmt.Sprintf("type %s = %s.%s\n\n", ref.Name, ref.ImportAlias, ref.SourceGoName))
		case "phantom":
			b.WriteString(fmt.Sprintf("// %s → %s\n", ref.Name, ref.TechnicalModel))
			b.WriteString(fmt.Sprintf("type %s struct {\n\tsdk.Model `sumeru:\"model=%s\"`\n}\n\n",
				ref.Name, ref.TechnicalModel))
		}
	}
	return b.String()
}

