// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("base",
		&CoreCompany{},
		&CoreCurrency{},
		&CoreCurrencyRate{},
		&CoreGroup{},
		&CorePartner{},
		&CoreUser{},
		&CoreUserAPIKey{},
		&CoreUserIdentity{},
		&CoreUserLog{},
		&CoreUserTrustedDevice{},
		&ResConfigSettings{},
		&SysAuthProvider{},
		&SysFieldAccess{},
		&UomCategory{},
		&UomUom{},
	)
}
