// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("base",
		&CoreCity{},
		&CoreCompany{},
		&CoreCountry{},
		&CoreCountryState{},
		&CoreCurrency{},
		&CoreGroup{},
		&CoreLang{},
		&CorePartner{},
		&CoreUser{},
		&CoreUserAPIKey{},
		&CoreUserLog{},
		&ResConfigSettings{},
		&SysActivity{},
		&SysAttachment{},
		&SysAudit{},
		&SysBulkImport{},
		&SysConfigParameter{},
		&SysFieldAccess{},
		&SysReportAction{},
		&SysSequence{},
		&SysTranslation{},
	)
}
