package report

import (
	"strings"

	"github.com/gpdf-dev/gpdf/document"
	"github.com/gpdf-dev/gpdf/pdf"
	gtemplate "github.com/gpdf-dev/gpdf/template"
)

// DocumentLayout holds company branding for printable documents.
type DocumentLayout struct {
	CompanyName string
	Street      string
	City        string
	Phone       string
	Email       string
	LogoURL     string
	FooterText  string
	PaperFormat string // A4, Letter
}

// DefaultDocumentLayout returns a minimal layout when company settings are unavailable.
func DefaultDocumentLayout(companyName string) DocumentLayout {
	name := strings.TrimSpace(companyName)
	if name == "" {
		name = "Sumeru"
	}
	return DocumentLayout{
		CompanyName: name,
		PaperFormat: PageSizeA4,
		FooterText:  "Generated by Sumeru",
	}
}

// ApplyLayoutHeader renders company header block on a PDF page.
func ApplyLayoutHeader(page *gtemplate.PageBuilder, layout DocumentLayout, title string) {
	page.AutoRow(func(r *gtemplate.RowBuilder) {
		r.Col(8, func(c *gtemplate.ColBuilder) {
			c.Text(strings.TrimSpace(layout.CompanyName), gtemplate.FontSize(14), gtemplate.Bold())
			if layout.Street != "" {
				c.Text(layout.Street, gtemplate.FontSize(9))
			}
			cityLine := strings.TrimSpace(strings.Join([]string{layout.City, layout.Phone}, " · "))
			if cityLine != "" && cityLine != "·" {
				c.Text(cityLine, gtemplate.FontSize(9))
			}
			if layout.Email != "" {
				c.Text(layout.Email, gtemplate.FontSize(9), gtemplate.TextColor(pdf.Gray(0.4)))
			}
		})
		r.Col(4, func(c *gtemplate.ColBuilder) {
			if t := strings.TrimSpace(title); t != "" {
				c.Text(t, gtemplate.FontSize(16), gtemplate.Bold(), gtemplate.AlignRight())
			}
		})
	})
	page.AutoRow(func(r *gtemplate.RowBuilder) {
		r.Col(12, func(c *gtemplate.ColBuilder) {
			c.Spacer(document.Mm(4))
		})
	})
}

// ApplyLayoutFooter renders a footer line on the last page section.
func ApplyLayoutFooter(page *gtemplate.PageBuilder, layout DocumentLayout) {
	footer := strings.TrimSpace(layout.FooterText)
	if footer == "" {
		return
	}
	page.AutoRow(func(r *gtemplate.RowBuilder) {
		r.Col(12, func(c *gtemplate.ColBuilder) {
			c.Spacer(document.Mm(6))
			c.Text(footer, gtemplate.FontSize(8), gtemplate.TextColor(pdf.Gray(0.5)), gtemplate.AlignCenter())
		})
	})
}
